/*************************************************************************
 * Copyright (c) 2022-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 *
 * See LICENSE for license information.
 ************************************************************************/

#include "rtc_dispatch.h"

#include <cstdint>
#include <string>

#include "../common.h"
#include "../util/rtc.h"
#include "../util/string.h"

// Embedded NVRTC source string (generated by CMake make_string_header_from_file).
#include "string_code_activation_rtc_activation_kernel_cu.h"

namespace transformer_engine {
namespace rtc_act {

namespace {

// Fully-qualified rtc_act dtype name used in the NVRTC name expression.
const char *type_name(DType d) {
  switch (d) {
    case DType::kFloat32:
      return "::transformer_engine::rtc_act::fp32";
    case DType::kFloat16:
      return "::transformer_engine::rtc_act::fp16";
    case DType::kBFloat16:
      return "::transformer_engine::rtc_act::bf16";
    case DType::kFloat8E4M3:
      return "::transformer_engine::rtc_act::fp8e4m3";
    case DType::kFloat8E5M2:
      return "::transformer_engine::rtc_act::fp8e5m2";
    default:
      NVTE_ERROR("Unsupported dtype for activation NVRTC path");
  }
}

}  // namespace

int fwd_act_id(NVTE_Activation_Type act) {
  switch (act) {
    case NVTE_Activation_Type::GELU:
      return ACT_GELU;
    case NVTE_Activation_Type::QGELU:
      return ACT_QGELU;
    case NVTE_Activation_Type::SILU:
      return ACT_SILU;
    case NVTE_Activation_Type::RELU:
      return ACT_RELU;
    case NVTE_Activation_Type::SRELU:
      return ACT_SRELU;
    default:
      NVTE_ERROR("Activation type not supported by the NVRTC activation path yet");
  }
}

int bwd_act_id(NVTE_Activation_Type act) {
  switch (act) {
    case NVTE_Activation_Type::GELU:
      return ACT_DGELU;
    case NVTE_Activation_Type::QGELU:
      return ACT_DQGELU;
    case NVTE_Activation_Type::SILU:
      return ACT_DSILU;
    case NVTE_Activation_Type::RELU:
      return ACT_DRELU;
    case NVTE_Activation_Type::SRELU:
      return ACT_DSRELU;
    default:
      NVTE_ERROR("Activation type not supported by the NVRTC activation path yet");
  }
}

void run(const NVTETensor x_, const NVTETensor grad_, NVTETensor output_, int act_id, bool is_bwd,
         cudaStream_t stream) {
  const Tensor *x = convertNVTETensorCheck(x_);
  const Tensor *grad = (grad_ != nullptr) ? convertNVTETensorCheck(grad_) : nullptr;
  Tensor *output = convertNVTETensorCheck(output_);

  // First-draft scope: per-tensor (delayed) scaling or high-precision, rowwise only.
  NVTE_CHECK(output->scaling_mode == NVTE_DELAYED_TENSOR_SCALING,
             "Activation NVRTC path currently supports only delayed/per-tensor scaling "
             "(or high-precision) output.");
  NVTE_CHECK(output->has_data() && !output->has_columnwise_data(),
             "Activation NVRTC path currently supports only rowwise output.");

  const size_t N = x->numel();
  const DType itype = x->dtype();
  const DType otype = output->dtype();
  const bool fp8_out = is_fp8_dtype(otype);

  // FP8 metadata (null for high-precision output).
  float *scale = fp8_out ? reinterpret_cast<float *>(output->scale.dptr) : nullptr;
  float *amax = fp8_out ? reinterpret_cast<float *>(output->amax.dptr) : nullptr;
  float *scale_inv = fp8_out ? reinterpret_cast<float *>(output->scale_inv.dptr) : nullptr;
  if (amax != nullptr) {
    // amax is accumulated with atomicMax in the kernel, so it must start at 0.
    NVTE_CHECK_CUDA(cudaMemsetAsync(amax, 0, sizeof(float), stream));
  }

  // Compile (once per distinct kernel) via NVRTC.
  const std::string label =
      concat_strings("act,a=", act_id, ",b=", static_cast<int>(is_bwd), ",i=",
                     static_cast<int>(itype), ",o=", static_cast<int>(otype));
  const std::string name =
      concat_strings("&::transformer_engine::rtc_act::act_kernel<", act_id, ", ",
                     (is_bwd ? "true" : "false"), ", ", type_name(itype), ", ", type_name(otype),
                     ">");
  auto &mgr = rtc::KernelManager::instance();
  if (!mgr.is_compiled(label)) {
    mgr.compile(label, name, string_code_activation_rtc_activation_kernel_cu,
                "activation_kernel.cu");
  }

  if (N == 0) {
    return;
  }

  // Launch parameters: scalar grid-stride kernel.
  constexpr int threads = 256;
  size_t blocks = (N + threads - 1) / threads;
  if (blocks > 65535) {
    blocks = 65535;
  }

  void *x_ptr = x->data.dptr;
  void *grad_ptr = (grad != nullptr) ? grad->data.dptr : nullptr;
  void *y_ptr = output->data.dptr;
  std::uint64_t n = static_cast<std::uint64_t>(N);

  mgr.launch(label, dim3(static_cast<unsigned int>(blocks)), dim3(threads), 0, stream, x_ptr,
             grad_ptr, y_ptr, scale, amax, scale_inv, n);
}

}  // namespace rtc_act
}  // namespace transformer_engine
